### ISSUE TITLE
Logo source file?

### ISSUE THREAD

**Issue by sindresorhus** [argentumproject/argentum#13]
Where can I find the source file or SVG (not PNG) of the project logo?

I would like to submit it to https://github.com/cjdowner/cryptocurrency-icons

**Comment by sindresorhus** [comment]
I have vectorized the logo for you now: https://github.com/atomiclabs/cryptocurrency-icons/issues/188

**Comment by protonn** [comment]
Very much appreciate the new logo file.
Somebody made another, is this not an acceptable Vector image? https://github.com/argentumproject/argentum/blob/master/share/pixmaps/argentum.eps
