### ISSUE TITLE
invalid use of incomplete type

### ISSUE THREAD

**Issue by cipig** [argentumproject/argentum#14]
Error on compile:
```
In file included from chain.cpp:9:0:
bignum.h:64:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
```

**Comment by protonn** [comment]
Which Linux distribution?

**Comment by cipig** [comment]
debian 9 (stretch)

**Comment by protonn** [comment]
Need to use openssl 1.0.1k
Alternatively, follow this to build use the pre-defined dependencies.
https://github.com/argentumproject/argentum/blob/master/depends/README.md
