### ISSUE TITLE
configure: error: Found Berkeley DB other than 5.1

### ISSUE THREAD

**Issue by pradeep1008** [argentumproject/argentum#8]
Got the following error while I installed with bash builder.sh :

configure: error: Found Berkeley DB other than 5.1, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)
make: *** No targets specified and no makefile found.  Stop.

after the error it shows:
finished and can be found in CoinBuilds/Argentum/src/ Make sure you sudo strip Coind and coin-cli if it exists, copy to /usr/bin

But Coind file is missing.

Please help. How to fix?

**Comment by protonn** [comment]
Use these instructions to build with BDB 5.1.29. Scroll down the page to Berkeley DB. Let me know if you have issues. 

https://github.com/argentumproject/argentum/blob/master/doc/build-unix.md
